# Generated by Django 3.2.7 on 2021-09-28 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nameCode', models.CharField(max_length=128)),
                ('team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GNB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KAN', 'Kansas City Chiefs'), ('LAC', 'Los Angeles Chargers'), ('LAR', 'Los Angeles Rams'), ('LVR', 'Las Vegas Raiders'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NOR', 'New Orleans Saints'), ('NWE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SEA', 'Seattle Seahawks'), ('SFO', 'San Francisco 49ers'), ('TAM', 'Tampa Bay Buccaneers'), ('TEN', 'Tennesse Titans'), ('WAS', 'Washington Football Team'), ('2TM', 'Multiple Teams'), ('FA', 'Free Agent')], default='FA', max_length=3)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Runningback'), ('WR', 'Wide Receiver'), ('TE', 'Tight End')], default='WR', max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('gamesStarted', models.IntegerField(default=0)),
                ('passCompletions', models.IntegerField(default=0)),
                ('passAttempts', models.IntegerField(default=0)),
                ('passYards', models.IntegerField(default=0)),
                ('passTouchdowns', models.IntegerField(default=0)),
                ('passInterceptions', models.IntegerField(default=0)),
                ('rushAttempts', models.IntegerField(default=0)),
                ('rushYards', models.IntegerField(default=0)),
                ('rushYardsAttempt', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rushTouchdowns', models.IntegerField(default=0)),
                ('recTargets', models.IntegerField(default=0)),
                ('recReceptions', models.IntegerField(default=0)),
                ('recYards', models.IntegerField(default=0)),
                ('recYardsCatch', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('recTouchdowns', models.IntegerField(default=0)),
                ('fumbles', models.IntegerField(default=0)),
                ('fumblesLost', models.IntegerField(default=0)),
                ('allTouchdowns', models.IntegerField(default=0)),
                ('twoPointConversion', models.IntegerField(default=0)),
                ('twoPointConversionPass', models.IntegerField(default=0)),
                ('fantasyPoints', models.IntegerField(default=0)),
                ('fantasyPPR', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fantasyDK', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fantasyFD', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fantasyVBD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to='draft.Player')),
            ],
        ),
    ]
