# Generated by Django 3.2.7 on 2021-09-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20210928_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='allTouchdowns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantasyDK',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantasyFD',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantasyPPR',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantasyPoints',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantasyVBD',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fumblesLost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesPlayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesStarted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passAttempts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passCompletions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passInterceptions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passTouchdowns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passYards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='recReceptions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='recTargets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='recTouchdowns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='recYards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='recYardsCatch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushAttempts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushTouchdowns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushYards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushYardsAttempt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twoPointConversion',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twoPointConversionPass',
        ),
        migrations.AddField(
            model_name='player',
            name='all_touchdowns',
            field=models.IntegerField(default=0, verbose_name='TDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='completions',
            field=models.IntegerField(default=0, verbose_name='CMP'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_DK',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='DK'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_FD',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='FD'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_PPR',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='PPR'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_VBD',
            field=models.IntegerField(default=0, verbose_name='VBD'),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_points',
            field=models.IntegerField(default=0, verbose_name='FP'),
        ),
        migrations.AddField(
            model_name='player',
            name='fumbles_lost',
            field=models.IntegerField(default=0, verbose_name='FL'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='player',
            name='games_started',
            field=models.IntegerField(default=0, verbose_name='GS'),
        ),
        migrations.AddField(
            model_name='player',
            name='interceptions',
            field=models.IntegerField(default=0, verbose_name='INT'),
        ),
        migrations.AddField(
            model_name='player',
            name='pass_attempts',
            field=models.IntegerField(default=0, verbose_name='ATT'),
        ),
        migrations.AddField(
            model_name='player',
            name='passing_touchdowns',
            field=models.IntegerField(default=0, verbose_name='TDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='passing_yards',
            field=models.IntegerField(default=0, verbose_name='YDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='receiving_touchdowns',
            field=models.IntegerField(default=0, verbose_name='TDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='receiving_yards',
            field=models.IntegerField(default=0, verbose_name='YDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='receiving_yards_per_catch',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Y/R'),
        ),
        migrations.AddField(
            model_name='player',
            name='receptions',
            field=models.IntegerField(default=0, verbose_name='REC'),
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_attempts',
            field=models.IntegerField(default=0, verbose_name='ATT'),
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_touchdowns',
            field=models.IntegerField(default=0, verbose_name='TDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_yards',
            field=models.IntegerField(default=0, verbose_name='YDS'),
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_yards_per_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Y/A'),
        ),
        migrations.AddField(
            model_name='player',
            name='targets',
            field=models.IntegerField(default=0, verbose_name='TGT'),
        ),
        migrations.AddField(
            model_name='player',
            name='two_point_conversion',
            field=models.IntegerField(default=0, verbose_name='2PC'),
        ),
        migrations.AddField(
            model_name='player',
            name='two_point_conversion_pass',
            field=models.IntegerField(default=0, verbose_name='2PP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fumbles',
            field=models.IntegerField(default=0, verbose_name='FMB'),
        ),
    ]
