# Generated by Django 3.2.7 on 2021-09-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20210928_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nameCode',
            new_name='name_code',
        ),
    ]
