# Generated by Django 3.2.7 on 2021-09-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_rename_namecode_player_name_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rushing_attempts',
            new_name='rush_attempts',
        ),
    ]
