# Generated by Django 3.2.7 on 2021-09-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_rename_name_code_player_name_code_fb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='position_POS',
        ),
    ]
