# Generated by Django 3.2.7 on 2021-09-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_rename_games_played_player_games_played_g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='games_started',
            new_name='games_started_GS',
        ),
    ]
