# Generated by Django 3.2.7 on 2021-09-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_rename_completions_player_completions_cmp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pass_attempts',
            new_name='pass_attempts_ATT',
        ),
    ]
