# Generated by Django 3.2.7 on 2021-09-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0013_rename_passing_touchdowns_player_passing_touchdowns_tds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='interceptions',
            new_name='interceptions_INT',
        ),
    ]
