# Generated by Django 3.2.7 on 2021-09-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0014_rename_interceptions_player_interceptions_int'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rush_attempts',
            new_name='rush_attempts_ATT',
        ),
    ]
