# Generated by Django 3.2.7 on 2021-09-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0015_rename_rush_attempts_player_rush_attempts_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rushing_yards',
            new_name='rushing_yards_YDS',
        ),
    ]
