# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0017_rename_rushing_yards_per_attempt_player_rushing_yards_per_attempt_ypa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rushing_touchdowns',
            new_name='rushing_touchdowns_TDS',
        ),
    ]
