# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0018_rename_rushing_touchdowns_player_rushing_touchdowns_tds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='targets',
            new_name='targets_TGT',
        ),
    ]
