# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0019_rename_targets_player_targets_tgt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='receptions',
            new_name='receptions_REC',
        ),
    ]
