# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0020_rename_receptions_player_receptions_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='receiving_yards',
            new_name='receiving_yards_YDS',
        ),
    ]
