# Generated by Django 3.2.7 on 2021-09-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0025_rename_fumbles_lost_player_fumbles_lost_fl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='all_touchdowns',
            new_name='all_touchdowns_TDS',
        ),
    ]
