# Generated by Django 3.2.7 on 2021-09-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0027_rename_two_point_conversion_player_two_point_conversion_2pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='two_point_conversion_pass',
            new_name='two_point_conversion_pass_2PP',
        ),
    ]
