# Generated by Django 3.2.7 on 2021-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0028_rename_two_point_conversion_pass_player_two_point_conversion_pass_2pp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fantasy_points',
            new_name='fantasy_points_FP',
        ),
    ]
