# Generated by Django 3.2.7 on 2021-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0029_rename_fantasy_points_player_fantasy_points_fp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fantasy_PPR',
            new_name='fantasy_PPR_PPR',
        ),
    ]
