# Generated by Django 3.2.7 on 2021-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0030_rename_fantasy_ppr_player_fantasy_ppr_ppr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fantasy_DK',
            new_name='fantasy_DK_DK',
        ),
    ]
