# Generated by Django 3.2.7 on 2021-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0031_rename_fantasy_dk_player_fantasy_dk_dk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fantasy_FD',
            new_name='fantasy_FD_FD',
        ),
    ]
