# Generated by Django 3.2.7 on 2021-09-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0032_rename_fantasy_fd_player_fantasy_fd_fd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fantasy_VBD',
            new_name='fantasy_VBD_VBD',
        ),
    ]
