# Generated by Django 3.2.7 on 2021-09-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0033_rename_fantasy_vbd_player_fantasy_vbd_vbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GNB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KAN', 'Kansas City Chiefs'), ('LAC', 'Los Angeles Chargers'), ('LAR', 'Los Angeles Rams'), ('LVR', 'Las Vegas Raiders'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NOR', 'New Orleans Saints'), ('NWE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SEA', 'Seattle Seahawks'), ('SFO', 'San Francisco 49ers'), ('TAM', 'Tampa Bay Buccaneers'), ('TEN', 'Tennesse Titans'), ('WAS', 'Washington Football Team'), ('MUL', 'Multiple Teams'), ('FA', 'Free Agent')], default='FA', max_length=3, verbose_name='Team'),
        ),
    ]
