# Generated by Django 3.2.7 on 2021-10-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0035_league_draftedplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.league'),
        ),
    ]
