# Generated by Django 3.2.7 on 2021-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0036_fantasyteam_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='commissioner',
            field=models.BooleanField(default=False),
        ),
    ]
