# Generated by Django 3.2.7 on 2021-10-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0037_fantasyteam_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
