# Generated by Django 3.2.7 on 2021-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0038_league_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
