# Generated by Django 3.2.7 on 2021-10-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0039_fantasyteam_active'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DraftDetails',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('drafted', models.DateTimeField(auto_now=True)),
        #         ('fantasyTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.fantasyteam')),
        #         ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
        #     ],
        # ),
        # migrations.AlterField(
        #     model_name='fantasyteam',
        #     name='players',
        #     field=models.ManyToManyField(through='draft.DraftDetails', to='draft.Player'),
        # ),
    ]
