# Generated by Django 3.2.7 on 2021-10-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0040_auto_20211015_1342'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='fantasyteam',
        #     name='players',
        # ),
    ]
