# Generated by Django 3.2.7 on 2021-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0041_remove_fantasyteam_players'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='fantasyteam',
        #     name='players',
        #     field=models.ManyToManyField(related_name='depreciated_players', to='draft.Player'),
        # ),
        # migrations.AddField(
        #     model_name='fantasyteam',
        #     name='roster',
        #     field=models.ManyToManyField(through='draft.DraftDetails', to='draft.Player'),
        # ),
    ]
