# Generated by Django 3.2.7 on 2021-10-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0042_auto_20211015_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='players',
            field=models.ManyToManyField(related_name='depreciated_players', to='draft.Player'),
        ),
        migrations.CreateModel(
            name='DraftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafted', models.DateTimeField(auto_now=True)),
                ('fantasyTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.fantasyteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='roster',
            field=models.ManyToManyField(through='draft.DraftDetails', to='draft.Player'),
        ),
    ]
