# Generated by Django 3.2.7 on 2021-10-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0043_auto_20211015_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='draftedPlayers',
        ),
    ]
