# Generated by Django 3.2.7 on 2021-10-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0045_remove_fantasyteam_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftdetails',
            name='fantasyTeam',
        ),
        migrations.AddField(
            model_name='draftdetails',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.league'),
        ),
    ]
