# Generated by Django 3.2.7 on 2021-10-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0046_auto_20211015_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draftedPlayers',
            field=models.ManyToManyField(through='draft.DraftDetails', to='draft.Player'),
        ),
    ]
