# Generated by Django 3.2.7 on 2021-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0047_league_draftedplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='players',
            field=models.ManyToManyField(to='draft.Player'),
        ),
    ]
