# Generated by Django 3.2.7 on 2021-10-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0048_alter_fantasyteam_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftdetails',
            options={'ordering': ['drafted']},
        ),
    ]
