# Generated by Django 3.2.7 on 2021-11-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0050_league_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('name', 'league')},
        ),
    ]
