# Generated by Django 3.2.7 on 2021-11-08 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0051_alter_fantasyteam_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('manager', 'league'), ('name', 'league')},
        ),
    ]
