# Generated by Django 3.2.7 on 2021-11-09 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0052_alter_fantasyteam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
